export const enContent = {
  locale: "en",
  route: "/",
  seo: {
    title: "Zsolt Kovács | Senior / Lead Full-Stack Software Engineer",
    description: "Senior / Lead Full-Stack Software Engineer with 17+ years of experience in .NET, Angular, software architecture and AI-native development.",
  },
  person: { name: "Zsolt Kovács", location: "Budapest, Hungary" },
  nav: {
    items: [
      { id: "summary", href: "#summary", label: "Professional Summary" },
      { id: "expertise", href: "#expertise", label: "Core Expertise" },
      { id: "ai-native", href: "#ai-native", label: "AI-Native Software Engineering" },
      { id: "project", href: "#fithub", label: "Selected Project — FitHub" },
      { id: "experience", href: "#experience", label: "Professional Experience" },
      { id: "education", href: "#education", label: "Education" },
      { id: "languages", href: "#languages", label: "Languages & Additional Technologies" },
      { id: "contact", href: "#contact", label: "Contact" },
    ],
  },
  hero: {
    title: "Senior / Lead Full-Stack Software Engineer",
    tagline: ".NET | Angular | AI-Native Software Development",
  },
  summary: "Senior / Lead Full-Stack Software Engineer with 17+ years of experience designing and delivering business applications and web systems. Strong hands-on background in C#, .NET, ASP.NET Core, Angular/TypeScript, software architecture, data access and distributed systems. Extensive practical experience with AI-native development: coding agents are integrated into the full software development lifecycle, from requirements and specifications to implementation, debugging, testing, code review and refactoring. Comfortable taking technical ownership from application design through Dockerized Linux infrastructure and production observability.",
  expertise: [
    { id: "ai-engineering", title: "AI Engineering", items: ["OpenAI Codex", "Codex CLI", "Claude Code", "Cursor", "VS Code", "AI Coding Agents", "Agentic Development", "Spec-Driven Development (SDD)", "AI-Driven Debugging", "MCP", "Agent Skills", "Prompt & Context Engineering"] },
    { id: "backend-architecture", title: "Backend & Architecture", items: ["C#", ".NET 10", "C# 14", "ASP.NET Core", "Entity Framework Core 10", "REST APIs", "CQRS", "Vertical Slice Architecture", "Hangfire", "Worker Services"] },
    { id: "frontend", title: "Frontend", items: ["Angular 22", "TypeScript", "Tailwind CSS", "Responsive Web Design"] },
    { id: "data-messaging", title: "Data & Messaging", items: ["PostgreSQL 18", "SQL Server", "pg_trgm", "Dapper", "Redis", "MongoDB", "RabbitMQ", "MassTransit"] },
    { id: "security", title: "Security", items: ["ASP.NET Core Identity", "JWT & Refresh Tokens", "OAuth/OpenID", "role-based authorization", "secure secret management"] },
    { id: "infrastructure-observability", title: "Infrastructure & Observability", items: ["Linux", "Debian", "Docker", "Docker Compose", "Hetzner Cloud/VPS", "Caddy", "Cloudflare", "OpenTelemetry", "Grafana Cloud", "Alloy", "Prometheus", "Loki", "Tempo", "GitHub Actions"] },
  ],
  aiNative: [
    { id: "spec-driven-development", description: "Spec-Driven Development (SDD) for feature discovery, requirements, specifications, implementation plans and agent-executable development tasks." },
    { id: "coding-agents", description: "Coding agents for repository analysis, architecture/design support, implementation, AI-driven debugging and root-cause analysis, testing, code review and refactoring." },
    { id: "mcp-agent-skills", description: "Model Context Protocol (MCP) and agent skills to provide tools, project knowledge and external-system context to development agents." },
    { id: "daily-workflow", description: "Daily AI-native coding workflows in VS Code use OpenAI Codex / Codex CLI, Claude Code and Cursor, supported by prompt engineering and context engineering." },
  ],
  project: {
    id: "fithub", title: "FitHub — Independent SaaS Project", period: "2025 - Present", url: "https://www.fithub.hu",
    description: "Designed and built a modern SaaS product end-to-end, covering application architecture, backend, frontend, database, infrastructure, deployment and production operations.",
    stack: "Application stack: C# 14, .NET 10, ASP.NET Core, Entity Framework Core 10, Angular 22, TypeScript, Tailwind CSS, PostgreSQL 18 and Hangfire.",
    infrastructure: "Built a Docker/Docker Compose multi-container production environment on Debian 13 / Hetzner VPS with Caddy and Cloudflare DNS, Proxy, Pages and R2.",
    observability: "Implemented production observability with OpenTelemetry, Grafana Cloud, Grafana Alloy, Prometheus, Loki and Tempo for metrics, distributed tracing and structured logging.",
    workflow: "Developed using an AI-native SDD workflow with Codex, Claude Code, Cursor, MCP and agent skills across planning, repository analysis, implementation, debugging, review and refactoring.",
  },
  experience: [
    { id: "mi-software", role: "Lead Software Developer", company: "MI Software", period: "Aug 2024 - Present", industry: "Education", bullets: ["Lead hands-on design and development of business-management software, contributing to architecture and technical decisions.", "Design and deliver greenfield projects from initial concept through implementation.", "Perform code reviews, mentor developers and support complex technical problem solving in business-critical systems."], technologies: ".NET 8, ASP.NET Core / REST APIs, Angular, Redis, RabbitMQ" },
    { id: "credit-management-group", role: "Software Architect", company: "Credit Management Group", period: "Apr 2018 - Aug 2024", industry: "Credit insurance", bullets: ["Designed and delivered custom full-stack software for internal and external business use.", "Defined architecture and technical solutions across multiple web projects.", "Combined hands-on implementation with software architecture responsibilities."], technologies: ".NET 6, CQRS, Angular" },
    { id: "xapt", role: "Senior Software Developer", company: "XAPT Solution Kft.", period: "Dec 2015 - Apr 2018", industry: "Business applications", bullets: ["Worked as a lead developer within R&D / product development.", "Designed and implemented business software and custom Microsoft CRM solutions."], technologies: "TypeScript, .NET Core, C#, Web API, OAuth2, Angular 2" },
    { id: "api-international", role: "Software Developer", company: "API International - Automotive Process Institute GmbH", period: "Jul 2012 - Dec 2015", industry: "Automotive diagnostics", bullets: ["Designed and developed desktop applications using WinForms, WPF, Windows Services and self-hosted web applications.", "Built web applications with ASP.NET MVC/Web API, SQL Server, ORMs, WCF and SignalR.", "Developed mobile applications for iOS."] },
    { id: "digital-line", role: "Web Developer", company: "Digital Line Informatics Kft.", period: "Jan 2009 - Jul 2012", industry: "Internet services", bullets: ["Built full-stack web applications with HTML/CSS, KnockoutJS/AngularJS and ASP.NET Web API/MVC with Entity Framework Code First.", "Deployed and hosted web applications in Microsoft Azure."] },
  ],
  education: { degree: "Bachelor of Science (BSc), Computer Software Engineering", institution: "Budapest University of Technology and Economics", period: "2009 - 2013", specialization: "Communication Networks and Services", thesis: "Secure authentication in web environment" },
  languages: [{ language: "Hungarian", level: "Native" }, { language: "English", level: "B2, professional working proficiency" }],
  additionalTechnologies: [".NET Framework", "WinForms", "WPF", "WCF", "SignalR", "ASP.NET MVC", "AngularJS", "KnockoutJS", "Kubernetes", "Azure", "TFVC", "Hyper-V"],
  contact: { phone: "+36 30 160 6530", email: "job@kovacs.id", linkedIn: "https://www.linkedin.com/in/zsoltmkovacs", gitHub: "https://github.com/zskovacs" },
  resumeUrl: null,
};
