export const huContent = {
  locale: "hu",
  route: "/hu/",
  seo: {
    title: "Kovács Zsolt | Senior / Lead Full-Stack Szoftverfejlesztő",
    description: "Senior / Lead Full-Stack Szoftverfejlesztő 17+ év tapasztalattal .NET, Angular, szoftverarchitektúra és AI-native fejlesztés területén.",
  },
  person: { name: "Kovács Zsolt", location: "Budapest, Magyarország" },
  nav: {
    items: [
      { id: "summary", href: "#summary", label: "Szakmai összefoglaló" },
      { id: "expertise", href: "#expertise", label: "Főbb szakterületek" },
      { id: "ai-native", href: "#ai-native", label: "AI-Native szoftverfejlesztés" },
      { id: "project", href: "#project", label: "Kiemelt projekt — FitHub" },
      { id: "experience", href: "#experience", label: "Szakmai tapasztalat" },
      { id: "education", href: "#education", label: "Tanulmányok" },
      { id: "languages", href: "#languages", label: "Nyelvek & további technológiák" },
      { id: "contact", href: "#contact", label: "Kapcsolat" },
    ],
  },
  hero: {
    title: "Senior / Lead Full-Stack Szoftverfejlesztő",
    tagline: ".NET | Angular | AI-Native szoftverfejlesztés",
  },
  summary: "Senior / Lead full-stack szoftverfejlesztő 17+ év tapasztalattal üzleti alkalmazások és webes rendszerek tervezésében és fejlesztésében. Erős, hands-on háttér C#, .NET, ASP.NET Core, Angular/TypeScript, szoftverarchitektúra, adatkezelés és elosztott rendszerek területén. Jelentős gyakorlati tapasztalatom van AI-native fejlesztési workflow-kban: a coding agenteket a teljes fejlesztési életciklusban használom a követelményektől és specifikációktól az implementáción, hibakeresésen és tesztelésen át a code review-ig és refaktorálásig. Az alkalmazás-architektúrától a Docker-alapú Linux infrastruktúráig és production observability-ig end-to-end szemlélettel dolgozom.",
  expertise: [
    { id: "ai-engineering", title: "AI Engineering", items: ["OpenAI Codex", "Codex CLI", "Claude Code", "Cursor", "VS Code", "AI Coding Agents", "Agentic Development", "Spec-Driven Development (SDD)", "AI-Driven Debugging", "MCP", "Agent Skills", "Prompt & Context Engineering"] },
    { id: "backend-architecture", title: "Backend & Architektúra", items: ["C#", ".NET 10", "C# 14", "ASP.NET Core", "Entity Framework Core 10", "REST API-k", "CQRS", "Vertical Slice Architecture", "Hangfire", "Worker Services"] },
    { id: "frontend", title: "Frontend", items: ["Angular 22", "TypeScript", "Tailwind CSS", "Responsive Web Design"] },
    { id: "data-messaging", title: "Adat & Messaging", items: ["PostgreSQL 18", "SQL Server", "pg_trgm", "Dapper", "Redis", "MongoDB", "RabbitMQ", "MassTransit"] },
    { id: "security", title: "Security", items: ["ASP.NET Core Identity", "JWT & Refresh Tokens", "OAuth/OpenID", "role-based authorization", "biztonságos secret management"] },
    { id: "infrastructure-observability", title: "Infrastruktúra & Observability", items: ["Linux", "Debian", "Docker", "Docker Compose", "Hetzner Cloud/VPS", "Caddy", "Cloudflare", "OpenTelemetry", "Grafana Cloud", "Alloy", "Prometheus", "Loki", "Tempo", "GitHub Actions"] },
  ],
  aiNative: [
    { id: "spec-driven-development", description: "Spec-Driven Development (SDD) használata feature discovery, követelmények, specifikációk, implementációs tervek és agentek által végrehajtható fejlesztési feladatok készítésére." },
    { id: "coding-agents", description: "Coding agentek használata repository analysis, architektúra és tervezés támogatása, implementáció, AI-driven debugging és root-cause analysis, tesztelés, code review és refaktorálás során." },
    { id: "mcp-agent-skills", description: "Model Context Protocol (MCP) és agent skills használata eszközök, projektismeret és külső rendszerek kontextusának agentekhez kapcsolására." },
    { id: "daily-workflow", description: "Napi AI-native coding workflow VS Code-ban OpenAI Codex / Codex CLI, Claude Code és Cursor használatával, prompt engineering és context engineering támogatással." },
  ],
  project: {
    id: "fithub", title: "FitHub — Önálló SaaS projekt", period: "2025 - jelenleg", url: "https://www.fithub.hu",
    description: "Modern SaaS termék end-to-end tervezése és fejlesztése, beleértve az alkalmazásarchitektúrát, backendet, frontendet, adatbázist, infrastruktúrát, deploymentet és production üzemeltetést.",
    stack: "Alkalmazás stack: C# 14, .NET 10, ASP.NET Core, Entity Framework Core 10, Angular 22, TypeScript, Tailwind CSS, PostgreSQL 18 és Hangfire.",
    infrastructure: "Docker/Docker Compose multi-container production környezet kialakítása Debian 13 / Hetzner VPS alapon, Caddy és Cloudflare DNS, Proxy, Pages és R2 használatával.",
    observability: "Production observability kialakítása OpenTelemetry, Grafana Cloud, Grafana Alloy, Prometheus, Loki és Tempo segítségével metrikákhoz, distributed tracinghez és structured logginghoz.",
    workflow: "AI-native SDD workflow használata Codex, Claude Code, Cursor, MCP és agent skills eszközökkel a tervezéstől és repository analysistől az implementáción, debuggingon, review-n és refaktoráláson át.",
  },
  experience: [
    { id: "mi-software", role: "Vezető szoftverfejlesztő", company: "MI Software", period: "2024 aug. - jelenleg", industry: "Oktatás", bullets: ["Ügyviteli szoftver hands-on tervezése és fejlesztése, részvétel az architekturális és technikai döntésekben.", "Greenfield projektek tervezése és megvalósítása a kezdeti koncepciótól az implementációig.", "Code review, fejlesztők mentorálása és komplex technikai problémák megoldásának támogatása üzletkritikus rendszerekben."], technologies: ".NET 8, ASP.NET Core / REST API-k, Angular, Redis, RabbitMQ" },
    { id: "credit-management-group", role: "Szoftverarchitekt", company: "Credit Management Group", period: "2018 ápr. - 2024 aug.", industry: "Hitelbiztosítás", bullets: ["Egyedi full-stack üzleti megoldások tervezése és fejlesztése belső és külső projektekhez.", "Architektúra és technikai megoldások kialakítása több webes projektben.", "Hands-on implementáció és szoftverarchitekt feladatok párhuzamos ellátása."], technologies: ".NET 6, CQRS, Angular" },
    { id: "xapt", role: "Senior szoftverfejlesztő", company: "XAPT Solution Kft.", period: "2015 dec. - 2018 ápr.", industry: "Üzleti alkalmazások", bullets: ["Lead developer szerep az R&D / termékfejlesztési csapatban.", "Üzleti szoftverek és Microsoft CRM egyedi megoldások tervezése és implementációja."], technologies: "TypeScript, .NET Core, C#, Web API, OAuth2, Angular 2" },
    { id: "api-international", role: "Szoftverfejlesztő", company: "API International - Automotive Process Institute GmbH", period: "2012 júl. - 2015 dec.", industry: "Autódiagnosztika", bullets: ["Asztali alkalmazások tervezése és fejlesztése WinForms, WPF, Windows Services és self-hosted web alkalmazások használatával.", "Webes alkalmazások fejlesztése ASP.NET MVC/Web API, SQL Server, ORM-ek, WCF és SignalR technológiákkal.", "iOS mobilalkalmazások fejlesztése."] },
    { id: "digital-line", role: "Webfejlesztő", company: "Digital Line Informatics Kft.", period: "2009 jan. - 2012 júl.", industry: "Internetes szolgáltatások", bullets: ["Full-stack webes alkalmazások fejlesztése HTML/CSS, KnockoutJS/AngularJS és ASP.NET Web API/MVC, Entity Framework Code First technológiákkal.", "Webes alkalmazások telepítése és üzemeltetése Microsoft Azure környezetben."] },
  ],
  education: { degree: "Mérnök Informatikus BSc", institution: "Budapesti Műszaki és Gazdaságtudományi Egyetem", period: "2009 - 2013", specialization: "Infokommunikációs hálózatok és szolgáltatások", thesis: "Biztonságos autentikáció webes környezetben" },
  languages: [{ language: "Magyar", level: "anyanyelv" }, { language: "Angol", level: "B2, szakmai munkavégzéshez használható szint" }],
  additionalTechnologies: [".NET Framework", "WinForms", "WPF", "WCF", "SignalR", "ASP.NET MVC", "AngularJS", "KnockoutJS", "Kubernetes", "Azure", "TFVC", "Hyper-V"],
  contact: { phone: "+36 30 160 6530", email: "job@kovacs.id", linkedIn: "https://www.linkedin.com/in/zsoltmkovacs", gitHub: "https://github.com/zskovacs" },
  resumeUrl: null,
};
